3. Getting the group of some gids kills the shell

M jao@cheese:~$ ls -fr /opt
Traceback (most recent call last):
  File "/home/jao/git/osh2/src/osh/main.py", line 45, in <module>
    main()
  File "/home/jao/git/osh2/src/osh/main.py", line 41, in main
    process_input(run_command)
  File "/home/jao/git/osh2/src/osh/main.py", line 26, in process_input
    handle_line(line)
  File "/home/jao/git/osh2/src/osh/main.py", line 15, in run_command
    command.execute()
  File "/home/jao/git/osh2/src/osh/core.py", line 238, in execute
    self.pipeline.receive(None)
  File "/home/jao/git/osh2/src/osh/core.py", line 198, in receive
    self.first_op.receive(x)
  File "/home/jao/git/osh2/src/osh/op/ls.py", line 109, in receive
    self.visit(file, 0)
  File "/home/jao/git/osh2/src/osh/op/ls.py", line 135, in visit
    self.visit(file, level + 1)
  File "/home/jao/git/osh2/src/osh/op/ls.py", line 135, in visit
    self.visit(file, level + 1)
  File "/home/jao/git/osh2/src/osh/op/ls.py", line 135, in visit
    self.visit(file, level + 1)
  [Previous line repeated 1 more time]
  File "/home/jao/git/osh2/src/osh/op/ls.py", line 131, in visit
    self.send_path(path)
  File "/home/jao/git/osh2/src/osh/op/ls.py", line 144, in send_path
    self.send(file)
  File "/home/jao/git/osh2/src/osh/core.py", line 100, in send
    self.receiver.receive_input_or_error(x)
  File "/home/jao/git/osh2/src/osh/core.py", line 115, in receive_input_or_error
    self.receive(normalize_output(x))
  File "/home/jao/git/osh2/src/osh/op/out.py", line 90, in receive
    out = out.render_full(self.use_color())
  File "/home/jao/git/osh2/src/osh/object/file.py", line 91, in render_full
    line = self._formatted_metadata()
  File "/home/jao/git/osh2/src/osh/object/file.py", line 131, in _formatted_metadata
    '{:8s}'.format(groupname(self.gid)),
  File "/home/jao/git/osh2/src/osh/util.py", line 17, in groupname
    return grp.getgrgid(gid).gr_name
KeyError: 'getgrgid(): gid not found: 143'

----------------------------------------------------------------------

5. Unspecified behavior for red

red . + does something given inputs of size 3. What is supposed to
happen? Document and test for it.

----------------------------------------------------------------------

9. Syntax error in map function not handled correctly

M jao@cheese:~/git/marcel/src/marcel$ ps | map (p: (p.pid, p.commandline.split()[0] if p.commandline else '')
Caught <class 'SyntaxError'>: invalid syntax (<string>, line 1)
  File "/home/jao/git/marcel/src/marcel/core.py", line 24, in arg_checker
    return check_and_convert(s)
  File "/home/jao/git/marcel/src/marcel/core.py", line 40, in check_function
    return marcel.function.Function(s)
  File "/home/jao/git/marcel/src/marcel/function.py", line 26, in __init__
    self.create_function()
  File "/home/jao/git/marcel/src/marcel/function.py", line 68, in create_function
    self.function = eval('lambda: ' + self.source, env.globals())
usage: map [-h] function
map: error: argument function: not a valid function

- There shouldn't be a stack, just an error message.

----------------------------------------------------------------------

10.



